# Generated by Django 4.1.3 on 2023-01-26 09:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=256)),
                ('number', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(2, 'Name must have more than 2 characters')])),
                ('number', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlassMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(2, 'Title must have more than 2 characters')])),
                ('text', models.TextField()),
                ('key', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Right',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('ogrn', models.BigIntegerField()),
                ('inn', models.BigIntegerField()),
                ('kpp', models.BigIntegerField()),
                ('legal_address', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(2, 'Title must have more than 2 characters')])),
                ('article', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(2, 'Title must have more than 2 characters')])),
                ('watch_size', models.IntegerField()),
                ('bracelet_size', models.IntegerField()),
                ('water_resistance', models.IntegerField()),
                ('price', models.FloatField()),
                ('count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bracelet_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracelet_color', to='store.color')),
                ('bracelet_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracelet_material', to='store.material')),
                ('buyers', models.ManyToManyField(related_name='watch_buyers', through='store.Order', to=settings.AUTH_USER_MODEL)),
                ('coating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.coating')),
                ('glass_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.glassmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='WatchStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='WatchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='img/')),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.watch')),
            ],
        ),
        migrations.AddField(
            model_name='watch',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.watchstyle'),
        ),
        migrations.AddField(
            model_name='watch',
            name='watch_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watch_color', to='store.color'),
        ),
        migrations.AddField(
            model_name='watch',
            name='watch_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watch_material', to='store.material'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.status'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='watch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.watch'),
        ),
    ]
