# Generated by Django 4.1.3 on 2023-01-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'ordered'), ('in_cart', 'in_cart'), ('canceled', 'canceled'), ('finished', 'finished')], default='in_cart', max_length=128),
        ),
    ]
