# Generated by Django 4.1.3 on 2023-01-19 11:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_contacts_contact_rename_rights_right'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='GlassMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='WatchStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(2, 'Name must have more than 2 characters')]),
        ),
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(2, 'Title must have more than 2 characters')]),
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(2, 'Title must have more than 2 characters')])),
                ('article', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(2, 'Title must have more than 2 characters')])),
                ('watch_size', models.IntegerField()),
                ('bracelet_size', models.IntegerField()),
                ('water_resistance', models.IntegerField()),
                ('price', models.FloatField()),
                ('count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bracelet_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracelet_color', to='store.color')),
                ('bracelet_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracelet_material', to='store.material')),
                ('coating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.coating')),
                ('glass_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.glassmaterial')),
                ('style', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.watchstyle')),
                ('watch_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watch_color', to='store.color')),
                ('watch_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watch_material', to='store.material')),
            ],
        ),
        migrations.CreateModel(
            name='WatchImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.image')),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.watch')),
            ],
            bases=('store.image',),
        ),
    ]
