# Generated by Django 4.1.3 on 2023-01-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_delete_status_alter_watchimage_watch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='price',
            field=models.IntegerField(),
        ),
    ]
