# Generated by Django 4.1.3 on 2023-01-26 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_feedback_number_alter_image_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default=1, upload_to='static/img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watchimage',
            name='watch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.watch'),
        ),
    ]
